import Vue from 'vue'
import {
  Button,
  FormModel,
  Form,
  Layout,
  Icon,
  Dropdown,
  Avatar,
  Menu,
  Tabs,
  Table,
  Result,
  Select,
  Input,
  DatePicker,
  Switch,
  Checkbox,
  Radio,
  Popconfirm,
  Alert,
  Modal,
  List,
  Card,
  Upload,
  InputNumber,
  Row,
  Col,
  Tag
} from 'ant-design-vue'

Layout.install(Vue)
Menu.install(Vue)
FormModel.install(Vue)
Form.install(Vue)
Radio.install(Vue)
Button.install(Vue)
Icon.install(Vue)
Dropdown.install(Vue)
Avatar.install(Vue)
Menu.install(Vue)
Tabs.install(Vue)
Table.install(Vue)
Result.install(Vue)
Select.install(Vue)
Input.install(Vue)
DatePicker.install(Vue)
Switch.install(Vue)
Checkbox.install(Vue)
Radio.install(Vue)
Popconfirm.install(Vue)
Alert.install(Vue)
Modal.install(Vue)
List.install(Vue)
Card.install(Vue)
Upload.install(Vue)
InputNumber.install(Vue)
Row.install(Vue)
Col.install(Vue)
Tag.install(Vue)
